# Generated by Django 3.2.6 on 2021-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Основные'), (1, 'Отроботонные'), (2, 'Исключение')], default=0, verbose_name='Статус малоимущих'),
            preserve_default=False,
        ),
    ]
