# Generated by Django 3.2.6 on 2021-08-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_needy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Основные'), (1, 'Отроботонные'), (2, 'Исключение')], null=True, verbose_name='Статус малоимущих'),
        ),
    ]
