# Generated by Django 3.2.6 on 2021-08-23 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_needy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needy',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='needy',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 8, 23, 7, 41, 2, 795653)),
        ),
    ]
