# Generated by Django 3.2.6 on 2021-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210823_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='createdAt',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
