# Generated by Django 3.2.6 on 2021-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_needy_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('total', models.IntegerField()),
            ],
        ),
    ]
