# Generated by Django 3.2.6 on 2021-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exportationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportationdata',
            name='total',
            field=models.CharField(max_length=255),
        ),
    ]
