# Generated by Django 3.2.6 on 2021-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exportationdata_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportationdata',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
