# Generated by Django 3.2.6 on 2021-08-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_exportationdata_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Детя', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='exportationdata',
            options={'verbose_name': 'Сохрененный данный', 'verbose_name_plural': 'Сохрененные данные'},
        ),
        migrations.AlterModelOptions(
            name='statushome',
            options={'verbose_name': 'Вид помощи дома', 'verbose_name_plural': 'Виды помощи домам'},
        ),
    ]
