# Generated by Django 3.2.6 on 2021-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210825_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='isDeadMan',
            field=models.BooleanField(default=False),
        ),
    ]
