# Generated by Django 3.2.6 on 2021-08-26 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_needy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='changed_onwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='needy',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 26, 17, 41, 16, 57314, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needy',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='needy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
