# Generated by Django 3.2.6 on 2021-08-26 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210826_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needy',
            old_name='createdAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='needy',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='needy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
