# Generated by Django 3.2.6 on 2021-08-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210826_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='getHelp',
            field=models.TextField(blank=True, null=True, verbose_name='Какую помощь получили'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок получение'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='statusHome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statushome', verbose_name='Статус дома'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='typeHelp',
            field=models.TextField(blank=True, null=True, verbose_name='Какая помощь необходима'),
        ),
    ]
