# Generated by Django 3.2.6 on 2021-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210826_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='helped',
            field=models.BooleanField(default=False, verbose_name='Помощь получили'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Помощь не полученные'), (1, 'Полученные'), (2, 'Исключение'), (3, 'Заново не полученные')], null=True, verbose_name='Статус малоимущих'),
        ),
    ]
