# Generated by Django 3.2.6 on 2021-09-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210826_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=255, null=True, verbose_name='Пол ребенка'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='statusHome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.statushome', verbose_name='Статус дома'),
        ),
    ]
