# Generated by Django 3.2.6 on 2021-09-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210923_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
